/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CorridaCavalo;

public class App {
   
    public static void main(String[] args) {
    	Equipe EqCvUm = new Equipe();
    	Equipe EqCvDois = new Equipe();
    	Equipe EqCvTres = new Equipe();
    	EqCvUm.v1 = new Cavalo (new FerraduraCvUm());
    	EqCvDois.v2 = new Cavalo (new FerraduraCvDois());
    	EqCvTres.v3 = new Cavalo (new FerraduraCvTres());
    	EqCvUm.v1.Acelerar(5);
    	EqCvDois.v2.Acelerar(5);
    	EqCvTres.v3.Acelerar(5);
    	
        System.out.println(EqCvUm.v1.Acelerar(5));
        System.out.println(EqCvDois.v2.Acelerar(4));
        System.out.println(EqCvTres.v3.Acelerar(3));
        
    }
}
